version: '3.8'

services:
  s3mock:
    image: adobe/s3mock
    container_name: s3mock-dev-server
    ports:
      - "9090:9090"
      - "9191:9191"
    environment:
      S3MOCK_INITIAL_BUCKETS: "mock-bucket"
    networks:
      - app-network

  app:
    image: aaasssk/zonbeozon:latest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/zonbeozon
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      DOCKER_S3MOCK_URL: s3mock:9090
      EXTERNAL_S3MOCK_URL: localhost:9090
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: zonbeozon
      MYSQL_USER: zon
      MYSQL_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  db-data:

networks:
  app-network: