spring:
  cache:
    type: caffeine

app:
  cache:
    channel-info-response:
      enabled: true
      name: channel-info-response
      expire-after-write-minutes: 2 #채널 유저수 변동은 직접 evict되지 않기 때문에 너무 길어지면 채널 유저수 반영이 느릴 수 있다.
      maximum-size: 1000


