spring:
  application:
    name: communityapp
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  config:
    import:
     - "classpath:cmc-api.yml"
     - "classpath:coin-info.yml"
     - "classpath:app-jwt.yml"

  messages:
      basename: ValidationMessages
      encoding: UTF-8

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:data/system-admin.sql
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

logging:
  level:
    com.zonbeozon.fiat.fetch: debug

    org:
      springframework:

        security: TRACE
#        transaction: DEBUG
#        orm:
#          jpa: DEBUG
        test:
          context:
            transaction: DEBUG
        web:
          socket: TRACE

        messaging: TRACE
        transaction: DEBUG

springdoc:
  api-docs:
    path: /local/v3/api-docs
  swagger-ui:
    path: /local/swagger-ui

frontend:
  uri: http://localhost:5173

view:
  count:
    # 5분 = 300초 = 300000 밀리초
    flush-interval-ms: 300000

outbox:
  schedule:
    initial-delay: 60000
    fixed-rate: 600000 #10분

system-admin:
  id: 1


